FROM rocker/tidyverse:3.5.1
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
RUN R -e 'remotes::install_cran("attempt")'
RUN R -e 'remotes::install_cran("dplyr")'
RUN R -e 'remotes::install_cran("DT")'
RUN R -e 'remotes::install_cran("flextable")'
RUN R -e 'remotes::install_cran("glue")'
RUN R -e 'remotes::install_cran("htmltools")'
RUN R -e 'remotes::install_cran("magrittr")'
RUN R -e 'remotes::install_cran("officer")'
RUN R -e 'remotes::install_cran("pkgload")'
RUN R -e 'remotes::install_cran("purrr")'
RUN R -e 'remotes::install_cran("rio")'
RUN R -e 'remotes::install_cran("shiny")'
RUN R -e 'remotes::install_cran("shinycssloaders")'
RUN R -e 'remotes::install_cran("shinyWidgets")'
RUN R -e 'remotes::install_cran("stringr")'
RUN R -e 'remotes::install_cran("tableone")'
RUN R -e 'remotes::install_cran("tidyverse")'
COPY tableOne_*.tar.gz /app.tar.gz
RUN R -e 'remotes::install_local("/app.tar.gz")'
CMD R -e "options('shiny.port'=$PORT,shiny.host='0.0.0.0');tableOne::run_app()"
